fotoblog/urls.py
import authentication
from django.contrib import admin, messages
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordResetView
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

import blog.views
from authentication.views import CustomPasswordChangeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LoginView.as_view(
        template_name='authentication/login.html',
        redirect_authenticated_user=True,
    ), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('recovery-password/', PasswordResetView.as_view(
        template_name='authentication/recovery-password.html',
        success_url='/',
    ), name='recovery-password'),
    path('change-password/', CustomPasswordChangeView.as_view(
        template_name='blog/change-password.html',
        success_url='/home/',
    ), name='change-password'),
    path('home/', blog.views.home, name='home'),
    path('profile/', authentication.views.profile_page, name='profile_page'),
    path('profile/edit/', authentication.views.edit_profile, name='edit_profile'),
    path('account/disable/', authentication.views.disable_account, name='disable_account'),
    path('follow-users/', blog.views.follow_users, name='follow_users'),
    path('my-photos/', blog.views.my_photos, name='my_photos'),
    path('photo/upload/', blog.views.photo_upload, name='photo_upload'),
    path('photo/<int:photo_id>/', blog.views.photo_detail, name='photo_detail'),
    path('photo/<int:photo_id>/edit', blog.views.edit_photo, name='edit_photo'),
    path('photo/upload-multiple/', blog.views.create_multiple_photos, name='create_multiple_photos'),
    path('profile/photo/upload', authentication.views.upload_profile_photo, name='profile_photo_upload'),
    path('blog/create', blog.views.blog_and_photo_upload, name='blog_create'),
    path('blog/<int:blog_id>', blog.views.view_blog, name='view_blog'),
    path('blog/<int:blog_id>/edit', blog.views.edit_blog, name='edit_blog'),
    path('signup/', authentication.views.signup_page, name='signup'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.conf import settings
from django.db import models
from PIL import Image


class Photo(models.Model):
    image = models.ImageField()
    title = models.CharField(max_length=128, blank=True, verbose_name='Titre')
    caption = models.CharField(max_length=128, blank=True, verbose_name='Légende')
    uploader = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)

    IMAGE_MAX_SIZE = (800, 800)

    def resize_image(self):
        image = Image.open(self.image)
        image.thumbnail(self.IMAGE_MAX_SIZE)
        image.save(self.image.path)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.resize_image()

    def __str__(self):
        if self.title is None or not self.title.strip():
            self.title = 'Untitled'
        return self.title


class Blog(models.Model):
    photo = models.ForeignKey(Photo, null=True, on_delete=models.SET_NULL, blank=True)
    title = models.CharField(max_length=128, verbose_name='Titre')
    content = models.CharField(max_length=5000, verbose_name='Contenu')
    contributors = models.ManyToManyField(settings.AUTH_USER_MODEL, through='BlogContributor',
                                          related_name='contributions')
    date_created = models.DateTimeField(auto_now_add=True)
    starred = models.BooleanField(default=False)
    word_count = models.IntegerField(null=True)

    def _get_word_count(self):
        return len(self.content.split(' '))

    def save(self, *args, **kwargs):
        self.word_count = self._get_word_count()
        super().save(*args, **kwargs)

    def __str__(self):
        if self.title is None or not self.title.strip():
            self.title = 'Untitled'
        return self.title


class BlogContributor(models.Model):
    contributor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    contribution = models.CharField(max_length=255, blank=True)

    class Meta:
        unique_together = ('contributor', 'blog')

templates/base.html
{% load static %}

<html>
<head>
    <title>FotoBlog - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
</head>
<body class="bg-image-cover">

{% if user.is_authenticated %}
<nav class='navbar navbar-expand-lg fixed-top bg-light shadow mb-5'>
    <div class='container-xl p-0'>
        <div class="d-flex align-items-center align-items-lg-end order-0">
            <button class='navbar-toggler collapsed' type='button' data-bs-toggle='collapse'
                    data-bs-target='#navbar-main'
                    aria-controls='navbar-main' aria-expanded='false' aria-label='Toggle navigation'>
                <span class="icon-bar bg-primary"></span>
                <span class="icon-bar bg-primary"></span>
                <span class="icon-bar bg-primary"></span>
            </button>
            <a class='navbar-brand'>
                <a class='text-decoration-none text-center' type='button' href="{% url 'home' %}">
                    <img
                            src="{% static 'img/app_photo_one_line.png' %}"
                            class="img-fluid"
                            style="height:4rem"
                            alt="app_logo"
                    >
                </a>
            </a>
        </div>
        <div class='collapse navbar-collapse order-2 d-lg-flex ms-lg-5' id='navbar-main'>
            <ul id="nav-items-gen" class='navbar-nav mt-3 mt-md-0 d-flex justify-content-center align-items-center'>
                {% if perms.blog.add_blog %}
                <li class='nav-item m-0'>
                    <a class='nav-link fw-bold' role='button' href="{% url 'blog_create' %}">Ecrire un post</a>
                </li>
                {% endif %}
                {% if perms.blog.add_photo %}
                <li class='nav-item m-0'>
                    <a class='nav-link fw-bold' role='button' href="{% url 'photo_upload' %}">Téléverser une photo</a>
                </li>
                <li class='nav-item m-0'>
                    <a class='nav-link fw-bold' role='button' href="{% url 'create_multiple_photos' %}">Téléverser plusieurs photos</a>
                </li>
                <li class='nav-item m-0'>
                    <a class='nav-link fw-bold' role='button' href="{% url 'my_photos' %}">Mes photos</a>
                </li>
                {% endif %}
                <li class='nav-item m-0'>
                    <a class='nav-link fw-bold' role='button' href="{% url 'follow_users' %}">Suivre des utilisateurs</a>
                </li>
            </ul>
        </div>
        <div class='d-flex justify-content-end align-items-center order-1 order-lg-last me-xl-3'>
            <div class="theme-control-toggle px-2 me-3 me-md-5">
                <input class="form-check-input ms-0 theme-control-toggle-input switchLogo" id="themeControlToggle"
                       type="checkbox" data-theme-control="theme" value="dark"/>
                <label class="mb-0 theme-control-toggle-label theme-control-toggle-light"
                       for="themeControlToggle" data-bs-toggle="tooltip" data-bs-placement="left"
                       title="Switch to light theme"><span class="fas fa-sun fs-0"></span></label>
                <label class="mb-0 theme-control-toggle-label theme-control-toggle-dark"
                       for="themeControlToggle" data-bs-toggle="tooltip" data-bs-placement="left"
                       title="Switch to dark theme"><span class="fas fa-moon fs-0"></span></label>
            </div>
            <a class="text-decoration-none fw-bold" role="button" data-bs-toggle="dropdown">
                <span class="first-name me-md-2">{{ request.user }}</span>
                <img class="img-profile rounded-circle" width="55" height="55"
                     src="{% if user.profile_pic %} {{ user.profile_pic.url }} {% else %} https://picsum.photos/55 {% endif %}"
                     alt="55x55">
            </a>
            <ul class='dropdown-menu dropdown-menu-end animated--fade-in-up' id="profil_dropdown">
                <li>
                    <a class='dropdown-item' type='button' href="{% url 'profile_page' %}">
                        <i class="fa-solid fa-user fs--1 me-2"></i>
                        Mon profil
                    </a>
                </li>
                <li>
                    <a class='dropdown-item' type='button' href="{% url 'change-password' %}"><i
                            class="fa-solid fa-key fs--1 me-2"></i>Modifier mot de passe</a>
                </li>
                <div class='dropdown-divider'></div>
                <li class="d-flex flex-row">
                    <a class='dropdown-item' type='button' href="{% url 'logout' %}"><i
                            class="fa-solid fa-right-from-bracket fs--1 me-2"></i>Se déconnecter</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% endif %}

{% if messages %}
{% for message in messages %}
<div class="alert {% if message.tags == 'success' %} alert-success {% else %} alert-danger {% endif %} alert-dismissible fade show"
     role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <strong class="alert-heading">{{ message }}</strong>
</div>
{% endfor %}
{% endif %}

{% block content %}{% endblock %}

{% block scripts %}
{% if user.is_authenticated %}
<script src="{% static 'js/header.js' %}"></script>
{% endif %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://kit.fontawesome.com/9414e04596.js" crossorigin="anonymous"></script>
{% endblock scripts %}
</body>
</html>